### ISSUE TITLE
Docker variable errors during build

### ISSUE THREAD

**Issue by msvgeek** [Nine-Minds/alga-psa#134]
Hello! I stumbled across your project and wanted to play with it a bit. Following the "Complete Setup Guide" I was able to get it up and running, but I wanted to let you know that the docker-compose file doesn't pull in any of the secrets it seems. Example below. Maybe it doesn't mean anything, but after getting the server spun up ("Production CE" still spun it up on port 3000) I took a look via Yacht and sure enough, all of the env variable are set to blank or defaults, and not what I set in the .env file (for email at least). And maybe I'm just a little dense this morning, but even though it all spun up anyway, I can't figure out what creds I'm supposed to log in with initially.

`WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.`

**Comment by RobertAtNineMinds** [comment]
Hi! I can answer one of the questions right away. If you look at the server console output, you will see a username and password you can use to login once you bring up the application.

Many of the secrets are actually loaded from the docker secrets file that is mounted in the container, and so you wouldn't expect to see them as environment variables.

I will take a look at all of the ones you mentioned above and make sure those are actually setting / being considered correctly.

**Comment by msvgeek** [comment]
I knew I was missing something! Thank you! FWIW, that was just a blurb of the errors during deployment. I think pretty much every env variable threw an exception.

**Comment by RobertAtNineMinds** [comment]
It may be the case that #214 fixes the remainder of this issue for you.

**Comment by Jamie-SpotOnTech** [comment]
After setting everything up as per the setup_guide.md and running docker compose ps this (below) is what is returned. Changing variables in the server/.env file has no effect on anything that I can see, and while I'm able to spin up the app and log in, if I bring the containers down and try to bring them up again after making changes to the .env file, docker to spin the containers back up. Any ideas? 

WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "EXPOSE_HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_NAME_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_USER_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_PASSWORD_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "EXPOSE_HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_NAME_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_USER_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_PASSWORD_HOCUSPOCUS" variable is not set. Defaulting to a blank string.
WARN[0000] The "REDIS_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_IS_FORMAT_JSON" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "NEXTAUTH_SESSION_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "EXPOSE_SERVER_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_ENABLE" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_FROM" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "NEXTAUTH_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERIFY_EMAIL_ENABLED" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_IS_FULL_DETAILS" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_TYPE" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_TOKEN" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "NEXTAUTH_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_IS_FORMAT_JSON" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_EXTERNAL_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "KEY_LENGTH" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_EXTERNAL_HTTP_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "SALT_BYTES" variable is not set. Defaulting to a blank string.
WARN[0000] The "ITERATION" variable is not set. Defaulting to a blank string.
WARN[0000] The "APP_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_TYPE" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_ENABLED_FILE_LOGGING" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_LEVEL" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOCUSPOCUS_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_ENABLE" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_USERNAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "ALGORITHM" variable is not set. Defaulting to a blank string.
WARN[0000] The "TOKEN_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_FROM" variable is not set. Defaulting to a blank string.
WARN[0000] The "NEXTAUTH_SESSION_EXPIRES" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_IS_FULL_DETAILS" variable is not set. Defaulting to a blank string.
WARN[0000] The "LOG_DIR_PATH" variable is not set. Defaulting to a blank string.
WARN[0000] The "EXPOSE_SERVER_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "VERIFY_EMAIL_ENABLED" variable is not set. Defaulting to a blank string.
WARN[0000] The "PROJECT_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] /root/alga-psa/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
NAME                  IMAGE                                COMMAND                  SERVICE    CREATED          STATUS          PORTS
sebastian_postgres    ankane/pgvector:latest               "docker-entrypoint.s…"   postgres   55 minutes ago   Up 55 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
sebastian_redis       alga-psa-redis                       "./entrypoint.sh"        redis      55 minutes ago   Up 55 minutes   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp
sebastian_server_ce   ghcr.io/nine-minds/alga-psa:latest   "/bin/sh -c 'export …"   server     55 minutes ago   Up 55 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
sebastian_setup_ce    ghcr.io/nine-minds/alga-psa:latest   "/app/setup/entrypoi…"   setup      55 minutes ago   Up 55 minutes   3000/tcp

**Comment by RobertAtNineMinds** [comment]
Take a look at #212 and let me know if my last comment about pulling the latest updates and pointing to the server/.env file resolves the issue you are facing.

**Comment by Jamie-SpotOnTech** [comment]
Will give it a try and let you know. Thank you, kindly.

**Comment by Jamie-SpotOnTech** [comment]
So after executing the steps outlined in #212 I'm able to log in with the canned credentials and can see that it grabbed variables from the secrets/.env file, but now there are some features, data that are seemingly missing, I guess. For instance: When you create a user after the update, there are no predefined roles in the Primary Roles drop down, anymore. Things like that.

**Comment by Jamie-SpotOnTech** [comment]
Outside of that, we're pretty excited about this project.

**Comment by RobertAtNineMinds** [comment]
Hi @Jamie-SpotOnTech yeah we are working through our project plan as quickly as we can. I think it might be helpful to make more of that public so it's clear what's finished and what we're still working through.

**Comment by Jamie-SpotOnTech** [comment]
So it's not fully functional for production, further testing, correct?

**Comment by Jamie-SpotOnTech** [comment]
Now when I try to log a test ticket, I get this:
sebastian_server_ce      | error: insert into "tickets" ("assigned_to", "attributes", "category_id", "channel_id", "company_id", "contact_name_id", "entered_at", "entered_by", "priority_id", "status_id", "subcategory_id", "tenant", "ticket_number", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) returning * - duplicate key value violates unique constraint "tickets_tenant_ticket_number_unique"
sebastian_server_ce      |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:283:98)
sebastian_server_ce      |     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:122:29)
sebastian_server_ce      |     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:35:38)
sebastian_server_ce      |     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
sebastian_server_ce      |     at Socket.emit (node:events:514:28)
sebastian_server_ce      |     at addChunk (node:internal/streams/readable:376:12)
sebastian_server_ce      |     at readableAddChunk (node:internal/streams/readable:349:9)
sebastian_server_ce      |     at Readable.push (node:internal/streams/readable:286:10)
sebastian_server_ce      |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
sebastian_server_ce      |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
sebastian_server_ce      |   length: 202,
sebastian_server_ce      |   severity: 'ERROR',
sebastian_server_ce      |   code: '23505',
sebastian_server_ce      |   detail: undefined,
sebastian_server_ce      |   hint: undefined,
sebastian_server_ce      |   position: undefined,
sebastian_server_ce      |   internalPosition: undefined,
sebastian_server_ce      |   internalQuery: undefined,
sebastian_server_ce      |   where: undefined,
sebastian_server_ce      |   schema: 'public',
sebastian_server_ce      |   table: 'tickets',
sebastian_server_ce      |   column: undefined,
sebastian_server_ce      |   dataType: undefined,
sebastian_server_ce      |   constraint: 'tickets_tenant_ticket_number_unique',
sebastian_server_ce      |   file: 'nbtinsert.c',
sebastian_server_ce      |   line: '664',
sebastian_server_ce      |   routine: '_bt_check_unique',
sebastian_server_ce      |   digest: '4254795915'
sebastian_server_ce      | }

**Comment by Jamie-SpotOnTech** [comment]
What I see in the app:
![Image](https://github.com/user-attachments/assets/d3a9f51e-e2a6-4351-964e-0cc720088243)
